// DOC-01..05/UI-29 (v1.71, doc 12) — "How it works" is a VISIBLE nav tab (the
// v1.71 commission ratifies the four-tab nav: Trading | Results | Calendar |
// How it works), but its actual content (the plain-English operations guide)
// is a LATER slice, still awaiting operator ratification. DOC-01 forbids
// rendering prose that hasn't been ratified against the spec — "the first
// draft is generated by the agent FROM THE RATIFIED SPEC ... and ratified by
// the operator before it renders anywhere" — so this renders an HONEST
// placeholder rather than any draft chapter text (the ruled build order,
// spec/05-architecture-ddd.md §10, forbids building slice 4 out of order).
export function HowItWorksPage() {
  return (
    <div className="how-it-works-page" data-testid="how-it-works-page">
      <h1>How it works</h1>
      <p className="gap-note" data-testid="how-it-works-placeholder">
        This guide is awaiting ratified content (DOC-01). The how-it-works chapters
        (doc 12) have not yet been ratified by the operator, so no draft prose renders
        here — never a fabricated or half-finished guide. Once ratified, this page
        renders the guide from that single source, stamped "describes spec vX.YY"
        (DOC-05) and banners any mismatch with the running build instead of pretending
        currency.
      </p>
    </div>
  );
}
