"""Auto-generated by tools/gen_phase1_stubs.py — prose TC stubs (Phase 1).

One failing stub per test case in spec/04-test-cases.md that has no
gherkin block. Each becomes a real test in its build phase; the stub
keeps scripts/check_traceability.py green on coverage while pytest
stays honestly red. Titles are the spec's own words.
"""
