"""Auto-generated by tools/gen_phase1_stubs.py — prose TC stubs (Phase 1).

One failing stub per test case in spec/04-test-cases.md that has no
gherkin block. Each becomes a real test in its build phase; the stub
keeps scripts/check_traceability.py green on coverage while pytest
stays honestly red. Titles are the spec's own words.
"""


# TC-ENT-03 — ENT-04/ENT-05: quantity equals contracts_per_entry; a day never exceeds max_entries_per_day fills.
def test_tc_ent_03():
    raise NotImplementedError("TC-ENT-03: prose test case not implemented (Phase 1 red)")


# TC-ORD-04 — EC-ENT-06 partial fill: (a) balanced partial — 1 of 2 condors filled at cancel ⇒ filled condor kept and protected (stops placed), quantity recorded; (b) unbalanced-leg anomaly injected via fake broker ⇒ completion attempted for partial_fix_seconds, else filled legs flattened; no unbalanced position remains; critical alert fired.
def test_tc_ord_04():
    raise NotImplementedError("TC-ORD-04: prose test case not implemented (Phase 1 red)")


# TC-STP-02 — STP-02 parametrization: for each pct in {95, 100, ..., 300} × each stop_basis ∈ {short_premium, total_credit, per_side}, triggers match the formulas (per_side formulas stay verified in the domain even while gated); values outside the pct set or basis set are rejected by config validation (doc 06); SELECTING per_side is rejected `allocation_unverified` per STP-02d (v1.43).
def test_tc_stp_02():
    raise NotImplementedError("TC-STP-02: prose test case not implemented (Phase 1 red)")


# TC-STP-03 — STP-02 intraday change / EC-STP-07: pct changed 95→150 (and basis per_side→total_credit) after entry 1 ⇒ entry 1 stops unchanged, entry 2 uses the new values.
def test_tc_stp_03():
    raise NotImplementedError("TC-STP-03: prose test case not implemented (Phase 1 red)")


# TC-STP-05 — EC-STP-02 crash between fill and stop placement: restart ⇒ REC-04 places stops; assert idempotency (no duplicates if one stop had actually been accepted).
def test_tc_stp_05():
    raise NotImplementedError("TC-STP-05: prose test case not implemented (Phase 1 red)")


# TC-STP-08 — STP-05/UC-12 stop independence: with a working stop, simulate bot disconnect; on reconnect the stop order is still working at the (fake, then paper-integration) broker with unbroken timestamps.
def test_tc_stp_08():
    raise NotImplementedError("TC-STP-08: prose test case not implemented (Phase 1 red)")


# TC-STP-09 — STP-03/EC-STP-08: with stop_limit configured, a triggered-unfilled stop is cancelled/replaced with market after stop_limit_escalation_seconds.
def test_tc_stp_09():
    raise NotImplementedError("TC-STP-09: prose test case not implemented (Phase 1 red)")


# TC-STP-11 — EC-STP-06: stop filled while bot down ⇒ on restart the missed event is synthesized and LEX begins.
def test_tc_stp_11():
    raise NotImplementedError("TC-STP-11: prose test case not implemented (Phase 1 red)")


# TC-STP-13 — STP-05a (contract test, sandbox): document the observed trigger source (last trade vs NBBO/mark) for a single-leg SPXW stop; test fails with an actionable message if single-leg option stops are rejected — build MUST NOT proceed past this failure.
def test_tc_stp_13():
    raise NotImplementedError("TC-STP-13: prose test case not implemented (Phase 1 red)")


# TC-NLE-07 — NLE-05/UI-13: preview endpoint returns per-side estimates for a candidate pct when the market is open, UNAVAILABLE when closed/stale; changing pct in the selector recomputes without submitting anything.
def test_tc_nle_07():
    raise NotImplementedError("TC-NLE-07: prose test case not implemented (Phase 1 red)")


# TC-LEX-06 — LEX-08/EC-LEX-03: fill-during-replace race ⇒ broker truth adopted; double-fill (short position created) ⇒ immediate buy-back + critical alert.
def test_tc_lex_06():
    raise NotImplementedError("TC-LEX-06: prose test case not implemented (Phase 1 red)")


# TC-LEX-07 — LEX-09: late fill after presumed cancel ⇒ P&L corrected from broker records.
def test_tc_lex_07():
    raise NotImplementedError("TC-LEX-07: prose test case not implemented (Phase 1 red)")


# TC-LEX-09 — EC-LEX-06 restart mid-ladder: ladder resumes from persisted step, working order rediscovered by key.
def test_tc_lex_09():
    raise NotImplementedError("TC-LEX-09: prose test case not implemented (Phase 1 red)")


# TC-CLS-02 — UC-14/UI-16: Close trade fires **instantly with no confirmation dialog** (Bug #16), closes via CLS, clears any armed TPF floor, tags the report `manual`; failures render as a toast, never a blocking dialog; a rapid double-click produces exactly one close (idempotency, TC-CLS-03). On a WORKING entry the action is Cancel entry (CLS-03), also instant. Flatten-all still requires the typed FLATTEN confirmation (TC-FLT-01).
def test_tc_cls_02():
    raise NotImplementedError("TC-CLS-02: prose test case not implemented (Phase 1 red)")


# TC-API-01 — EC-API-01/REC-06: token expiry renewed proactively; forced auth failure ⇒ backoff, entries blocked, alert.
def test_tc_api_01():
    raise NotImplementedError("TC-API-01: prose test case not implemented (Phase 1 red)")


# TC-API-02 — EC-API-02: under injected 429s, exit-side requests are always sent before queued entry-side requests; none dropped.
def test_tc_api_02():
    raise NotImplementedError("TC-API-02: prose test case not implemented (Phase 1 red)")


# TC-API-03 — EC-API-04: unknown broker position adopted; naked short protected (stop placed) before any other action; entries blocked until reconciled.
def test_tc_api_03():
    raise NotImplementedError("TC-API-03: prose test case not implemented (Phase 1 red)")


# TC-SIM-03 — SIM-04 money: an entry fill posts credit minus per-leg fees to the ledger; open entries consume margin per the spread requirement and release on close; insufficient simulated BP skips the entry (rejected_bp); settlement posts against the real closing level; the ledger survives container restart (REC-07).
def test_tc_sim_03():
    raise NotImplementedError("TC-SIM-03: prose test case not implemented (Phase 1 red)")


# TC-SIM-04 — SIM-05 pipeline identity: an identical scripted day through SimulatedBroker and FakeBroker(live-shape) produces the same event sequence, NLE calibration records, and a PNL-04 reconcile against the sim transaction ledger; every report stamped PAPER.
def test_tc_sim_04():
    raise NotImplementedError("TC-SIM-04: prose test case not implemented (Phase 1 red)")
