#!/usr/bin/env python3
"""Generate the Phase-1 red suite: BDD step stubs + prose TC stubs.

Reads the operator's locked artifacts (tests/features/*.feature generated by
scripts/extract_features.py, and spec/04-test-cases.md) and emits:

  tests/bdd/test_tc_*.py    one module per feature: pytest-bdd bindings with
                            every step defined and raising NotImplementedError
  tests/prose/test_prose_tc_stubs.py
                            one failing stub per prose TC (no gherkin block),
                            named tc_<id> so scripts/check_traceability.py
                            counts it as implemented-or-stubbed

Rerun after any spec amendment + re-extraction:
    python tools/gen_phase1_stubs.py

A Scenario Outline without an Examples table is invalid Gherkin: such a
feature gets a blocked-on-amendment module instead of bindings (Phase-1
finding; see the PR summary).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEATURES = ROOT / "tests" / "features"
BDD_OUT = ROOT / "tests" / "bdd"
PROSE_OUT = ROOT / "tests" / "prose"
DOC04 = ROOT / "spec" / "04-test-cases.md"

PRIMARY = ("Given", "When", "Then")
CONTINUATION = ("And", "But")


def parse_feature(path: Path):
    """Return (ordered unique (kind, text) steps, outline_without_examples)."""
    steps: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    current: str | None = None
    has_outline = False
    has_examples = False
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if line.startswith("Scenario Outline:"):
            has_outline, current = True, None
            continue
        if line.startswith(("Scenario:", "Feature:")):
            current = None
            continue
        if line.startswith("Examples:"):
            has_examples = True
            continue
        for kw in PRIMARY + CONTINUATION:
            if line.startswith(kw + " "):
                text = line[len(kw) + 1 :].strip()
                kind = current if kw in CONTINUATION else kw.lower()
                if kw in PRIMARY:
                    current = kw.lower()
                if kind is None:
                    raise ValueError(f"{path.name}: continuation step before any primary step: {line!r}")
                if (kind, text) not in seen:
                    seen.add((kind, text))
                    steps.append((kind, text))
                break
    return steps, (has_outline and not has_examples)


def emit_bdd_module(tc: str, steps: list[tuple[str, str]], blocked: bool) -> str:
    mod = [
        f'"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for {tc}.',
        "",
        "Every step raises NotImplementedError: the harness plumbing is in place,",
        "the system under test is not (HANDOFF.md Phase-1 red starting condition).",
        "Regenerate after spec amendments: python tools/gen_phase1_stubs.py",
        '"""',
    ]
    if blocked:
        mod += [
            "",
            "",
            f"def test_{tc.lower().replace('-', '_')}_blocked_on_spec_amendment():",
            f'    raise NotImplementedError(',
            f'        "{tc}: Scenario Outline has no Examples table (invalid Gherkin) - "',
            f'        "blocked on the operator-ratified spec amendment; regenerate after "',
            f'        "re-extraction (tools/gen_phase1_stubs.py)"',
            f"    )",
        ]
        return "\n".join(mod) + "\n"

    needs_parsers = any("<" in text for _, text in steps)
    imports = "from pytest_bdd import given, parsers, scenarios, then, when" if needs_parsers else "from pytest_bdd import given, scenarios, then, when"
    mod += ["", imports, "", f'scenarios("../features/{tc}.feature")']
    for kind, text in steps:
        params = re.findall(r"<(\w+)>", text)
        mod.append("")
        mod.append("")
        if params:
            pattern = re.sub(r"<(\w+)>", r"{\1}", text)
            mod.append(f"@{kind}(parsers.parse({pattern!r}))")
            mod.append(f"def _({', '.join(params)}):")
        else:
            mod.append(f"@{kind}({text!r})")
            mod.append("def _():")
        mod.append(f'    raise NotImplementedError("{tc}: not implemented (Phase 1 red)")')
    return "\n".join(mod) + "\n"


def emit_prose_module(prose: list[tuple[str, str]]) -> str:
    mod = [
        '"""Auto-generated by tools/gen_phase1_stubs.py — prose TC stubs (Phase 1).',
        "",
        "One failing stub per test case in spec/04-test-cases.md that has no",
        "gherkin block. Each becomes a real test in its build phase; the stub",
        "keeps scripts/check_traceability.py green on coverage while pytest",
        "stays honestly red. Titles are the spec's own words.",
        '"""',
    ]
    for tc, title in prose:
        name = tc.lower().replace("-", "_")
        mod.append("")
        mod.append("")
        mod.append(f"# {tc} — {title}" if title else f"# {tc}")
        mod.append(f"def test_{name}():")
        mod.append(f'    raise NotImplementedError("{tc}: prose test case not implemented (Phase 1 red)")')
    return "\n".join(mod) + "\n"


def main() -> int:
    features = sorted(FEATURES.glob("*.feature"))
    if not features:
        print("no feature files found — run scripts/extract_features.py first", file=sys.stderr)
        return 1
    BDD_OUT.mkdir(parents=True, exist_ok=True)
    PROSE_OUT.mkdir(parents=True, exist_ok=True)
    for old in BDD_OUT.glob("test_tc_*.py"):
        old.unlink()

    blocked_tcs, step_count = [], 0
    for f in features:
        steps, blocked = parse_feature(f)
        if blocked:
            blocked_tcs.append(f.stem)
        step_count += len(steps)
        out = BDD_OUT / f"test_{f.stem.lower().replace('-', '_')}.py"
        out.write_text(emit_bdd_module(f.stem, steps, blocked), encoding="utf-8")

    doc = DOC04.read_text(encoding="utf-8-sig")
    all_tcs = []
    titles = {}
    for m in re.finditer(r"\*\*(TC-[A-Z]+-\d{2})\*\*(?:\s*[—–-]\s*(.*))?", doc):
        if m.group(1) not in titles:
            all_tcs.append(m.group(1))
            titles[m.group(1)] = (m.group(2) or "").strip()
    feature_ids = {f.stem for f in features}
    prose = [(tc, titles[tc]) for tc in all_tcs if tc not in feature_ids]
    (PROSE_OUT / "test_prose_tc_stubs.py").write_text(emit_prose_module(prose), encoding="utf-8")

    print(
        f"generated {len(features)} BDD stub modules ({step_count} unique step defs, "
        f"{len(blocked_tcs)} blocked: {', '.join(blocked_tcs) or 'none'}) "
        f"and {len(prose)} prose TC stubs"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
