"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STP-14.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STP-14.feature")


@given('stop_basis = per_side, stop_loss_pct = 95, stop_rebate_markup = 0.50')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('the put stop trigger = round_to_tick(1.35 + 0.95*1.20 + 0.50)')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('the call stop trigger = round_to_tick(1.25 + 0.95*1.10 + 0.50)')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@given('stop_basis = total_credit and the same markup')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('both triggers = round_to_tick(0.95*2.30 + 0.50)')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@given('stop_rebate_markup = 0.00')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('triggers are byte-identical to the pre-markup formulas')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@given('a markup of 0.50 in force')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('the NLE estimate is computed from the markup-inclusive trigger')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('the calibration record for a stop event stores markup = 0.50')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@given('the operator sets markup 0.50 in the UI')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then('the setting displays the worst-case increase before saving  # UI-18')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@given('markup changed 0.00 -> 0.50 after entry 1 filled')
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")


@then("entry 1's resting stops are unchanged and entry 2 uses 0.50")
def _():
    raise NotImplementedError("TC-STP-14: not implemented (Phase 1 red)")
