"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STK-06.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, parsers, scenarios, then, when

scenarios("../features/TC-STK-06.feature")


@given("entry 3's target short put strike 5990 holds an existing long")
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('the short shifts to 5985 and the wing moves with it (width preserved)')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given('existing longs at 5990, 5985 and 5980 (the original and both shift targets)')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('the entry is SKIPPED with reason "strike_collision" and no order is submitted')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given("entry 1 is short 5990 and entry 3's selection also lands on 5990")
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('no shift occurs and the order is submitted')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then("both entries' fills and stops attribute correctly by order ID")
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given("the wing target already holds another entry's long")
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('no shift occurs')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given('the short places at its original strike')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given('the wing target 5940 holds an existing short position')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('the long shifts alone to 5935 (spread now 5 points wider)')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('RSK-04 evaluates the widened worst case before submission')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('five failed long shifts abort the entry with "strike_collision"')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given('an unfilled working order includes a long at 5990')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@when('the next entry wants a short at 5990')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('5990 is treated as blocked')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('an unfilled SHORT at 5990 does not block a new short there  # same type never blocks')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@given("the shifted short's premium falls below min_short_premium (or total net < min_total_credit)")
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")


@then('the entry is SKIPPED with reason "insufficient_credit"')
def _():
    raise NotImplementedError("TC-STK-06: not implemented (Phase 1 red)")
