"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-OWN-03.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-OWN-03.feature")


@given('the bot is short 2 x 5990 put (ledger = 2, stops resting for 2)')
def _():
    raise NotImplementedError("TC-OWN-03: not implemented (Phase 1 red)")


@when('the broker position becomes short 3 (foreign_delta = 1)')
def _():
    raise NotImplementedError("TC-OWN-03: not implemented (Phase 1 red)")


@then('a persistent shared-symbol warning is shown')
def _():
    raise NotImplementedError("TC-OWN-03: not implemented (Phase 1 red)")


@then('the resting stops remain for exactly 2')
def _():
    raise NotImplementedError("TC-OWN-03: not implemented (Phase 1 red)")


@then("a subsequent stop fill triggers LEX for exactly the bot's long quantity")
def _():
    raise NotImplementedError("TC-OWN-03: not implemented (Phase 1 red)")


@then('a Close trade on that entry submits orders for exactly 2')
def _():
    raise NotImplementedError("TC-OWN-03: not implemented (Phase 1 red)")
