"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ORD-02.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ORD-02.feature")


@given('the broker accepts the order but the submit response times out')
def _():
    raise NotImplementedError("TC-ORD-02: not implemented (Phase 1 red)")


@when('the bot queries by idempotency key')
def _():
    raise NotImplementedError("TC-ORD-02: not implemented (Phase 1 red)")


@then('it discovers the existing order and does NOT resubmit')
def _():
    raise NotImplementedError("TC-ORD-02: not implemented (Phase 1 red)")
