"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ENT-06.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ENT-06.feature")


@given('the session token expires in 200 seconds at T-60')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@when('the warm-up probe runs')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('the token is renewed before T-30')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('the 10:30 entry begins exactly on schedule with fresh quotes')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@given('the DXLink chain subscription is silently stale at T-60')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('the warm-up resubscribes and quotes are fresh (STK-04) at fire time')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@given('token renewal fails repeatedly from T-60')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('an alert is raised at T-10')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('at fire time the entry is SKIPPED with reason "invalid_session"')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('the entry time itself was never delayed')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@given('the bot finishes recovery at T-30')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")


@then('the warm-up probe runs immediately (compressed), not skipped')
def _():
    raise NotImplementedError("TC-ENT-06: not implemented (Phase 1 red)")
