"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STP-16.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STP-16.feature")


@given('shorts 3.00 + 2.00, wings 0.50 + 0.50, net credit 4.00, pct 95')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('both triggers = 3.80 exactly')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('one side stopped with the other expiring nets +20')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('both sides stopped nets -360')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('the same trade at pct 100')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('both triggers = 4.00, one-side nets 0, both-sides nets -400 exactly')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('net credit 3.60 at pct 95 (raw trigger 3.42)')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('the trigger floors to 3.40, never 3.50')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('net credit 3.10 at pct 95 (raw trigger 2.945)')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('the trigger floors to 2.90, never 2.95')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('vector 1 plus stop_rebate_markup 0.50')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('both triggers = 4.30')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('a one-side hit nets -30 plus long recovery   # the +20 guarantee is traded away by the dial')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('both sides nets -460')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('shorts 3.00 + 2.00 with wings 1.50 + 1.50 (net credit 2.00, raw trigger 1.90)')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('the trigger sits below the 3.00 short and the entry is SKIPPED "infeasible_stop"')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('net credit 3.37 at pct 95 (raw 3.2015, floors to 3.20) vs a 3.00 short')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('clearance is exactly 2 ticks and the entry is FEASIBLE   # rule is >=')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@given('vector 1 with stop_basis = total_credit')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")


@then('the trigger MUST be 3.80 and MUST NOT be 5.85')
def _():
    raise NotImplementedError("TC-STP-16: not implemented (Phase 1 red)")
