"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-NFR-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-NFR-01.feature")


@given('a broker REST call that hangs for 30 seconds (injected)')
def _():
    raise NotImplementedError("TC-NFR-01: not implemented (Phase 1 red)")


@when('the next scheduled entry time arrives during the hang')
def _():
    raise NotImplementedError("TC-NFR-01: not implemented (Phase 1 red)")


@then('the entry attempt begins on time')
def _():
    raise NotImplementedError("TC-NFR-01: not implemented (Phase 1 red)")


@then('the session probe, quote consumption and UI stream continue uninterrupted')
def _():
    raise NotImplementedError("TC-NFR-01: not implemented (Phase 1 red)")
