"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STP-15.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STP-15.feature")


@given('estimated net credit 2.00 at 95% (trigger 1.90) and the short put mid is 3.00')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@then('the entry is SKIPPED with reason "infeasible_stop" and no order is submitted')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@given('estimated net credit 4.00 (trigger 3.80) vs shorts at 3.00 and 2.00')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@then('triggers clear both fills by the minimum distance and stops are placed')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@given("fills land such that the actual trigger does not clear a short's fill")
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@then('no stop is placed for that entry')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@then('the entry closes via CLS-01 with initiator "infeasible_stop" and an alert')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@given('a rebate markup that lifts the trigger above fill + minimum distance')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")


@then('the entry is feasible   # STP-02b adds to the trigger before the check')
def _():
    raise NotImplementedError("TC-STP-15: not implemented (Phase 1 red)")
