"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-NLE-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-NLE-01.feature")


@given('a scripted put-side chain:')
def _():
    raise NotImplementedError("TC-NLE-01: not implemented (Phase 1 red)")


@given('stop trigger = 5.14 and nle_haircut_pct = 30')
def _():
    raise NotImplementedError("TC-NLE-01: not implemented (Phase 1 red)")


@then('implied move D = 45')
def _():
    raise NotImplementedError("TC-NLE-01: not implemented (Phase 1 red)")


@then('raw long estimate = 1.55, haircut estimate = 1.085')
def _():
    raise NotImplementedError("TC-NLE-01: not implemented (Phase 1 red)")


@then('estimated net loss = (5.14 - 1.35) - (1.085 - 0.15) = 2.855')
def _():
    raise NotImplementedError("TC-NLE-01: not implemented (Phase 1 red)")


@then('it is reported in $ and as % of the stop-basis credit')
def _():
    raise NotImplementedError("TC-NLE-01: not implemented (Phase 1 red)")
