"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STK-02.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, parsers, scenarios, then, when

scenarios("../features/TC-STK-02.feature")


@given('target_premium = 3.00, target_premium_tolerance = 0.10')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('adjacent put strikes with mids 3.10 and 2.85')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the short put strike is the 3.10 strike   # ceiling = 3.10 inclusive; richest qualifying wins')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the long put strike = short - wing_width   # STK-03, regardless of its cost')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('adjacent put strikes with mids 3.11 and 2.85')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the short put strike is the 2.85 strike   # 3.11 > 3.10 ceiling')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('adjacent put strikes with mids 3.25 and 2.85')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the short put strike is the 2.85 strike   # 3.25 above ceiling even though closer to target')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('every strike with valid quotes has mid > 3.10')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the entry is SKIPPED with reason "no_valid_strikes"')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('target_premium = 3.00 and both shorts fill their premium floor')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('in the morning the wings cost 1.00 each (total net = 3.90)')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('at the 12:30 entry the wings cost 2.10 each (total net = 1.90)')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the morning entry proceeds')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the 12:30 entry is SKIPPED with reason "insufficient_credit"  # STK-06: total NET < 2.00 aborts')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('the put side nets 0.10 after an expensive wing and the call side nets 2.20')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('both shorts collected >= min_short_premium')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the entry proceeds (total net 2.30 >= 2.00)   # per-side NET floor deliberately does not exist')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@given('the condor fills with short put 3.00 and long put 1.00')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('per_side stop math uses side net credit 2.00 (not 3.00)')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")


@then('the day report shows short premium and net credit as separate labelled figures  # UI-14')
def _():
    raise NotImplementedError("TC-STK-02: not implemented (Phase 1 red)")
