"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ENT-05.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ENT-05.feature")


@given("entry 2's order is still WORKING at 11:00 ET")
def _():
    raise NotImplementedError("TC-ENT-05: not implemented (Phase 1 red)")


@when("entry 3's scheduled time arrives")
def _():
    raise NotImplementedError("TC-ENT-05: not implemented (Phase 1 red)")


@then("entry 2's order is cancelled and cancellation confirmed")
def _():
    raise NotImplementedError("TC-ENT-05: not implemented (Phase 1 red)")


@then('any partial fill is resolved per EC-ENT-06 before entry 3 begins')
def _():
    raise NotImplementedError("TC-ENT-05: not implemented (Phase 1 red)")
