"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-SIM-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-SIM-01.feature")


@given('a condor limit at 2.30 net credit')
def _():
    raise NotImplementedError("TC-SIM-01: not implemented (Phase 1 red)")


@when('the real net mid touches 2.30 exactly')
def _():
    raise NotImplementedError("TC-SIM-01: not implemented (Phase 1 red)")


@then('the order does NOT fill')
def _():
    raise NotImplementedError("TC-SIM-01: not implemented (Phase 1 red)")


@when('the natural price satisfies 2.30 OR the mid reaches 2.35 (one tick through)')
def _():
    raise NotImplementedError("TC-SIM-01: not implemented (Phase 1 red)")


@then('the order fills all-or-nothing with per-leg prices allocated from current quotes')
def _():
    raise NotImplementedError("TC-SIM-01: not implemented (Phase 1 red)")
