"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-RSK-07.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-RSK-07.feature")


@given('one open condor, one side mid-LEX, one working entry order')
def _():
    raise NotImplementedError("TC-RSK-07: not implemented (Phase 1 red)")


@when('the process is killed and restarted')
def _():
    raise NotImplementedError("TC-RSK-07: not implemented (Phase 1 red)")


@then('within recovery_sla_seconds every short is covered by a confirmed resting stop')
def _():
    raise NotImplementedError("TC-RSK-07: not implemented (Phase 1 red)")


@then('the LEX ladder has resumed')
def _():
    raise NotImplementedError("TC-RSK-07: not implemented (Phase 1 red)")


@then('the stale entry order is cancelled (window elapsed)')
def _():
    raise NotImplementedError("TC-RSK-07: not implemented (Phase 1 red)")


@then('zero duplicate orders exist at the broker')
def _():
    raise NotImplementedError("TC-RSK-07: not implemented (Phase 1 red)")
