"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STK-07.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STK-07.feature")


@given('only 75% of strikes within the ATM band have marks at fire time')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('no strike selection occurs and the gate retries every chain_retry_seconds')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@when('the chain completes at T+20s (within the entry window)')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('selection proceeds normally')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@given('the chain never reaches chain_completeness_pct within entry_window_seconds')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('the entry is SKIPPED with reason "incomplete_chain" and no order is submitted')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@given('the completeness gate passes at 90%')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@given("the strike one step closer to the money than the walk's selection has no mark")
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('the selection is rejected and treated as a STK-10 failure (retry, then skip)')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@given('the strike one step closer to the money is marked BELOW the ceiling')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('the selection is rejected            # the walk should have selected that richer strike')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@given('the wing strike has no mark at fire time but appears at T+15s')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('the entry proceeds with the correct wing (no guessing, no immediate skip)')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@given('strikes outside the ATM band have no bids')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")


@then('the chain-integrity gate still passes')
def _():
    raise NotImplementedError("TC-STK-07: not implemented (Phase 1 red)")
