"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STK-03.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STK-03.feature")


@given("the short put's mid = 0.80 and min_short_premium = 1.00")
def _():
    raise NotImplementedError("TC-STK-03: not implemented (Phase 1 red)")


@then('the entry is SKIPPED with reason "insufficient_credit"')
def _():
    raise NotImplementedError("TC-STK-03: not implemented (Phase 1 red)")


@then('no order of any kind is submitted   # single-side entries prohibited')
def _():
    raise NotImplementedError("TC-STK-03: not implemented (Phase 1 red)")
