"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-FLT-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-FLT-01.feature")


@given('entry 1 OPEN (both sides), entry 2 with put side mid-LEX, entry 3 with a WORKING entry order, entry 4 OPEN with an armed TPF floor')
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@when('the operator confirms Flatten all')
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then("entry 3's order is cancelled (CLS-03), no close orders placed for its legs")
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then('entries 1, 2, 4 close via CloseEntry with initiator "manual_flatten"')
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then("entry 2's LEX ladder is superseded by an immediate marketable-limit close")
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then("entry 4's TPF floor is cleared")
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then('a scheduled entry arriving WHILE the flatten executes is SKIPPED (flatten_in_progress)')
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then('with the Stop Trading checkbox OFF, the next scheduled entry after completion fires normally into the clean book')
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")


@then('with the checkbox ON, subsequent entries are blocked until reset (Stop Trading persisted across restart)')
def _():
    raise NotImplementedError("TC-FLT-01: not implemented (Phase 1 red)")
