"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ENT-08.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ENT-08.feature")


@given('the operator presses the manual fire button at 10:07, outside any scheduled window')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@given('all ENT-03 gates pass')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@when('the OK-confirmation dialog is acknowledged')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('exactly one entry attempt runs through the identical pipeline')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('the entry is recorded with initiator "manual_entry"')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('it counts toward max_entries_per_day')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@given('the operator presses the manual fire button')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@when('the dialog is dismissed or times out')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('no order is submitted and no attempt is recorded')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@given('Stop Trading is ON')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@when('the operator presses the manual fire button and acknowledges OK')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('the attempt is refused with skip reason "blocked" shown on the card')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@given('open entries whose summed worst case leaves less headroom than the manual entry needs')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@when('the manual entry is confirmed')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('it is skipped with reason "max_day_risk"')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@when('the operator presses the button twice and confirms once')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")


@then('exactly one order exists (idempotency key per press-confirmation)')
def _():
    raise NotImplementedError("TC-ENT-08: not implemented (Phase 1 red)")
