"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-OWN-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-OWN-01.feature")


@given('the broker reports short 1 SPX 6050 call with no matching bot order fill')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")


@then('the position is marked FOREIGN')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")


@then('the bot never submits any order referencing 6050 calls (stop, close, or hedge)')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")


@then('it appears in no bot P&L or risk figure')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")


@then('a critical alert and persistent banner are raised')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")


@given('the FOREIGN position is an unprotected naked short in a moving market')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")


@then('the bot still submits no orders for it   # never guess operator intent')
def _():
    raise NotImplementedError("TC-OWN-01: not implemented (Phase 1 red)")
