"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-NFR-04.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-NFR-04.feature")


@given('a full simulated trading day')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('the fake transport counts exactly 1 persistent connection in the happy path')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@given('the hub replaced socket generation 2 with generation 3')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@when('late ticks from generation 2 arrive interleaved with generation 3 ticks')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('no generation-2 tick reaches the marks table and prices never move backwards in time')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('only the hub manager writes the marks table')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then("the one-shot fetcher's data path returns to its caller only")
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@given('the hub is sick and in an 8s backoff wait when an entry fires')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@when('the demand-reconnect succeeds within feed_demand_reconnect_seconds')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('the entry proceeds on the healed hub (no fetcher used)')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@given('the demand-reconnect fails')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('a one-shot fetcher returns a chain snapshot directly to the entry attempt')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('the snapshot passes chain-integrity gates before any selection')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('the marks table is untouched by the fetcher')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@given('demand-reconnect and fetcher both fail')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")


@then('the entry skips "data_unavailable", a LEX ladder freezes with its limit still working, TPF/DCY pause, an informational alert fires, and everything resumes on heal')
def _():
    raise NotImplementedError("TC-NFR-04: not implemented (Phase 1 red)")
