"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ORD-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ORD-01.feature")


@given('the entry order does not fill')
def _():
    raise NotImplementedError("TC-ORD-01: not implemented (Phase 1 red)")


@when('entry_reprice_seconds elapses 5 times')
def _():
    raise NotImplementedError("TC-ORD-01: not implemented (Phase 1 red)")


@then('the limit was repriced down one tick each time')
def _():
    raise NotImplementedError("TC-ORD-01: not implemented (Phase 1 red)")


@then('never below min_total_credit')
def _():
    raise NotImplementedError("TC-ORD-01: not implemented (Phase 1 red)")


@then('after the final attempt the order is cancelled and entry SKIPPED "unfilled_at_floor"')
def _():
    raise NotImplementedError("TC-ORD-01: not implemented (Phase 1 red)")
