"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ENT-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ENT-01.feature")


@given('the clock reaches 10:00:00 ET')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")


@when('the entry attempt begins within entry_window_seconds')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")


@then('a 4-leg condor limit order is submitted per ORD-01/ORD-02')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")


@given('the bot was down from 09:55 to 10:05 ET')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")


@when('the bot restarts at 10:05')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")


@then('entry 1 is marked SKIPPED with reason "missed_window"')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")


@then('no order for entry 1 is ever submitted')
def _():
    raise NotImplementedError("TC-ENT-01: not implemented (Phase 1 red)")
