"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-OWN-07.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-OWN-07.feature")


@given('entry 1 is OPEN with stops resting and was seen_open in the positions feed')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@when('the position disappears and the stop shows NOT filled, on two consecutive reconciles')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@then('all automation for the side stands down (no LEX, no TPF, no EOD close)')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@then('the bot submits NO orders and does NOT cancel its own leftover stop   # operator owns all cleanup')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@then('the critical alert lists the leftover stop with its open-a-long consequence')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@then("the alert's one-click Cancel-stop action cancels it when (and only when) clicked")
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@then('the side is marked CLOSED_EXTERNAL')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@given('the short is gone AND its stop order shows FILLED')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")


@then('the normal stop-out path runs (LEX) and no external-close event is emitted')
def _():
    raise NotImplementedError("TC-OWN-07: not implemented (Phase 1 red)")
