"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ENT-02.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, parsers, scenarios, then, when

scenarios("../features/TC-ENT-02.feature")


@given(parsers.parse('{gate_condition} is true at 10:30 ET'))
def _(gate_condition):
    raise NotImplementedError("TC-ENT-02: not implemented (Phase 1 red)")


@then(parsers.parse('entry 2 is SKIPPED with reason {reason}'))
def _(reason):
    raise NotImplementedError("TC-ENT-02: not implemented (Phase 1 red)")


@then('no order is submitted')
def _():
    raise NotImplementedError("TC-ENT-02: not implemented (Phase 1 red)")
