"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-LEX-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-LEX-01.feature")


@given('the short put stop filled and the long put quotes bid 2.00 / ask 2.30')
def _():
    raise NotImplementedError("TC-LEX-01: not implemented (Phase 1 red)")


@then('a limit sell at 2.15 is placed within lex_start_latency_ms')
def _():
    raise NotImplementedError("TC-LEX-01: not implemented (Phase 1 red)")


@when('lex_reprice_seconds elapses without fill')
def _():
    raise NotImplementedError("TC-LEX-01: not implemented (Phase 1 red)")


@then('the order is replaced at one tick lower recomputed from the CURRENT quote  # EC-LEX-05')
def _():
    raise NotImplementedError("TC-LEX-01: not implemented (Phase 1 red)")


@then('after lex_reprice_attempts unfilled replacements the fallback places a marketable limit at the current bid  # LEX-05')
def _():
    raise NotImplementedError("TC-LEX-01: not implemented (Phase 1 red)")
