"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-CLS-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-CLS-01.feature")


@given('two identical open entries A and B (same fills, same stops)')
def _():
    raise NotImplementedError("TC-CLS-01: not implemented (Phase 1 red)")


@when('entry A is closed via the UI "Close trade" button')
def _():
    raise NotImplementedError("TC-CLS-01: not implemented (Phase 1 red)")


@when('entry B is closed via a TPF floor trigger')
def _():
    raise NotImplementedError("TC-CLS-01: not implemented (Phase 1 red)")


@then('the sequence of broker requests (cancels, close orders, prices, quantities) is identical')
def _():
    raise NotImplementedError("TC-CLS-01: not implemented (Phase 1 red)")


@then('only the recorded initiator differs: "manual" vs "take_profit"')
def _():
    raise NotImplementedError("TC-CLS-01: not implemented (Phase 1 red)")
