"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STP-17.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STP-17.feature")


@given('the mark crosses the trigger and the broker stop fills within 6 seconds')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('the watchdog never alerts and never acts')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@given('the mark holds at or above trigger and the resting stop stays unfilled')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('a critical alert fires at 10 seconds')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('at 20 seconds the bot sends a marketable buy-to-close and cancels the resting stop')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('the side proceeds SIDE_STOPPED into LEX with initiator watchdog_escalation')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@given('the resting stop fills while the escalation order is in flight')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('the escalation aborts per ORD-08 and exactly one buy-back exists (order count = 1)')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@given('quotes go stale mid-breach')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('the watchdog clock pauses and resumes on fresh data; no action on stale marks')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")


@then('each watchdog_escalation record stores mark-at-breach, elapsed time, and fill price')
def _():
    raise NotImplementedError("TC-STP-17: not implemented (Phase 1 red)")
