"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-TPF-02.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, parsers, scenarios, then, when

scenarios("../features/TC-TPF-02.feature")


@given('the selector is open with profit 25% and level 20 enabled')
def _():
    raise NotImplementedError("TC-TPF-02: not implemented (Phase 1 red)")


@when('streamed profit falls to 24%')
def _():
    raise NotImplementedError("TC-TPF-02: not implemented (Phase 1 red)")


@then('level 20 greys out in place without reopening the selector  # 24 - 20 < 5')
def _():
    raise NotImplementedError("TC-TPF-02: not implemented (Phase 1 red)")


@given('the client submits level 20 based on its rendered profit of 25%')
def _():
    raise NotImplementedError("TC-TPF-02: not implemented (Phase 1 red)")


@given("the backend's own mark computes profit at 22%")
def _():
    raise NotImplementedError("TC-TPF-02: not implemented (Phase 1 red)")


@then('the request is rejected (not clamped) and the UI refreshes  # EC-TPF-04')
def _():
    raise NotImplementedError("TC-TPF-02: not implemented (Phase 1 red)")
