"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-TPF-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, parsers, scenarios, then, when

scenarios("../features/TC-TPF-01.feature")


@then('enabled levels are exactly {5, 10, 15, 20}')
def _():
    raise NotImplementedError("TC-TPF-01: not implemented (Phase 1 red)")


@then('25 and above are disabled with reason "too close - would trigger immediately"')
def _():
    raise NotImplementedError("TC-TPF-01: not implemented (Phase 1 red)")


@then('enabled levels are exactly {5, 10, ..., 70}')
def _():
    raise NotImplementedError("TC-TPF-01: not implemented (Phase 1 red)")


@then('75 and above are disabled')
def _():
    raise NotImplementedError("TC-TPF-01: not implemented (Phase 1 red)")


@then('the highest enabled level is 15   # 20 violates the 5-point gap (23 - 20 < 5)')
def _():
    raise NotImplementedError("TC-TPF-01: not implemented (Phase 1 red)")
