"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STP-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-STP-01.feature")


@given('stop_basis = short_premium')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@when('the condor fill is confirmed')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('the put stop trigger = round_to_tick(1.35 * (1 + 0.95))')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('the call stop trigger = round_to_tick(1.25 * (1 + 0.95))')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then("neither trigger depends on any long leg's allocated fill price")
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@given('stop_basis = total_credit')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('two buy-to-close stop-market orders (TIF Day) are working within the same processing turn')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('each trigger price = round_to_tick(0.95 * 2.30)')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('no stop exists on either long leg   # STP-06')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@given('stop_basis = per_side')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('the put stop trigger = round_to_tick(1.35 + 0.95 * 1.20)')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then('the call stop trigger = round_to_tick(1.25 + 0.95 * 1.10)')
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")


@then("side net credits are computed from the broker's allocated leg fills")
def _():
    raise NotImplementedError("TC-STP-01: not implemented (Phase 1 red)")
