"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-OWN-10.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-OWN-10.feature")


@given('the stop order shows cancelled with no bot-initiated cancel in the event log')
def _():
    raise NotImplementedError("TC-OWN-10: not implemented (Phase 1 red)")


@then('the bot does NOT re-place it')
def _():
    raise NotImplementedError("TC-OWN-10: not implemented (Phase 1 red)")


@then('the side is marked USER_UNPROTECTED with a critical alert')
def _():
    raise NotImplementedError("TC-OWN-10: not implemented (Phase 1 red)")


@then('the UI banner offers a one-click Re-protect action which places a fresh stop when clicked')
def _():
    raise NotImplementedError("TC-OWN-10: not implemented (Phase 1 red)")


@given('a short whose stop was never confirmed (crash before placement)')
def _():
    raise NotImplementedError("TC-OWN-10: not implemented (Phase 1 red)")


@then('REC-04 re-places the stop automatically   # OWN-11 applies only to non-bot cancels')
def _():
    raise NotImplementedError("TC-OWN-10: not implemented (Phase 1 red)")
