"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-ORD-06.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-ORD-06.feature")


@given('a resting stop whose cancel fails with "order no longer exists"')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@then('the order is marked dead and tracking stops')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@then('the cancel is never retried and protection is never re-added for a dead order')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@then('total requests for that order after the terminal response = 0')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@given('cancels failing with timeouts, then a cancel rejected because filled')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@then('the timeout case retries with backoff up to its cap')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@then('the filled case is handled as a fill (EC-API-06)')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@given('a cancel failure matching no known class')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")


@then('it is treated as transient with a hard retry cap and raises an alert at the cap')
def _():
    raise NotImplementedError("TC-ORD-06: not implemented (Phase 1 red)")
