"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-RSK-01.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, scenarios, then, when

scenarios("../features/TC-RSK-01.feature")


@given('two open condors and one LEX ladder in progress')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@when('Stop Trading is activated')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('no further entries occur')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('resting stops remain working')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('the LEX ladder continues            # risk-reducing work proceeds')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('TPF monitoring and the decay watcher continue')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@given('Flatten All is confirmed WITHOUT the Stop Trading checkbox')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('every bot entry closes via CLS')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('the next scheduled entry fires normally into the clean book')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@given('Stop Trading was active')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@when('the bot restarts')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")


@then('entries remain blocked until the operator resets ("Resume trading")')
def _():
    raise NotImplementedError("TC-RSK-01: not implemented (Phase 1 red)")
