"""Auto-generated by tools/gen_phase1_stubs.py — Phase-1 stubs for TC-STP-04.

Every step raises NotImplementedError: the harness plumbing is in place,
the system under test is not (HANDOFF.md Phase-1 red starting condition).
Regenerate after spec amendments: python tools/gen_phase1_stubs.py
"""

from pytest_bdd import given, parsers, scenarios, then, when

scenarios("../features/TC-STP-04.feature")


@given('the broker rejects stop placement stop_retry_attempts times')
def _():
    raise NotImplementedError("TC-STP-04: not implemented (Phase 1 red)")


@then('the affected side is flattened per unprotected_action')
def _():
    raise NotImplementedError("TC-STP-04: not implemented (Phase 1 red)")


@then('a critical alert is raised')
def _():
    raise NotImplementedError("TC-STP-04: not implemented (Phase 1 red)")


@then('total unprotected time <= stop_retry_seconds * stop_retry_attempts')
def _():
    raise NotImplementedError("TC-STP-04: not implemented (Phase 1 red)")
